baseURL = "https://docs.kolibricloud.ch/cloud-interfaces/"
languageCode = "en-us"
title = "Documentation to various interfaces"
googleAnalytics = "UA-117920007-1"
pygmentsUseClasses = true

[[menu.main]]
    pre = "<i class='fas fa-hand-point-right'></i>"
    name = "Overview"
    identifier = "overview"
    url = "/overview/"
    weight = 1

[[menu.main]]
    pre = "<i class='fas fa-plug'></i>"
    name = "Cloud API"
    identifier = "api"
    url = "/api/"
    weight = 2

[[menu.main]]
    pre = "<i class='fas fa-desktop'></i>"
    name = "Web App"
    identifier = "webapp"
    url = "/webapp/"
    weight = 3

[[menu.main]]
    pre = "<i class='fab fa-connectdevelop'></i>"
    name = "The KOLIBRI Ecosystem"
    identifier = "kolibri-ecosystem"
    url = "/kolibri-ecosystem/"
    weight = 4

[[menu.main]]
    pre = "<i class='fab fa-github'></i>"
    name = "Community & support"
    identifier = "community"
    url = "/community/"
    weight = 5

[params]
    version = "1.0.0"
